name: wrecklog
description: A simple vehicle dismantling and parts tracking app.
publish_to: "none"

version: 1.7.1+36

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  share_plus: ^9.0.0
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  in_app_purchase: ^3.2.3
  image_picker: ^1.1.2
  path: ^1.9.0
  photo_view: ^0.15.0
  package_info_plus: ^8.0.0
  gal: ^2.3.0
  archive: ^3.6.1
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  image: ^4.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/logo/

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: assets/icon/icon_fg.png
  image_path_ios: assets/icon/icon_ios.png
  adaptive_icon_foreground: assets/icon/icon_fg.png
  adaptive_icon_background: "#1A1A1A"
